-- AlterTable
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "tpId" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "stageTitle" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "contactType" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "leadStatusId" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "timeInStatus" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "inactiveDays" INTEGER;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "campaignId" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "lastCreditPulledDate" TIMESTAMP(3);
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "droppedDate" TIMESTAMP(3);
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "programStartDate" TIMESTAMP(3);
ALTER TABLE "ForthContact" ADD COLUMN IF NOT EXISTS "forthCreatedAt" TIMESTAMP(3);
